apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Specify auto scale by annotation"
  name: gatewayssl
spec:
  appliesToWorkloads:
    - ingresses.networking.k8s.io
  podDisruptive: false
  schematic:
    cue:
      template: |
        import "encoding/json"

        patch: {
            metadata: annotations: {
                "my.custom.autoscale.annotation": json.Marshal({
                    "minReplicas": parameter.min
                    "maxReplicas": parameter.max
                })
            }
        }
        parameter: {
            min: *1 | int
            max: *3 | int
        }