apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt.org
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: saltbo@foxmail.com
    privateKeySecretRef:
      name: letsencrypt.org
    solvers:
      - http01:
          ingress:
            class: nginx