apiVersion: batch/v1
kind: CronJob
metadata:
  name: acme-updater
spec:
  schedule: "2 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: updater
            image: neilpang/acme.sh
            imagePullPolicy: IfNotPresent
            command:
            - --cron
            - --renew-hook 
            - "acme.sh --deploy --deploy-hook qiniu -d saltbo.cn"
            env:
              - name: QINIU_CDN_DOMAIN
                value: "saltbo.cn .saltbo.cn"
            envFrom:
              - secretRef:
                  name: aksk-qiniu
            volumeMounts:
              - mountPath: /acme.sh
                name: acme
          restartPolicy: OnFailure
          volumes:
            - name: acme
              hostPath:
                path: /data/acme.sh
                type: DirectoryOrCreate