apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  name: local-default
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/default
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: usefor.saltbo.cn
          operator: In
          values:
          - boblab

# 待验证：Host目录必须提前创建