apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: bitwarden
spec:
  components:
    - name: bitwarden
      type: webservice
      properties:
        image: vaultwarden/server:1.26.0
        ports:
          - port: 80
        env:
          - name: DATABASE_URL
            value: "mysql://root:wV7ltEHtwdh7@mysql.infra.svc.cluster.local:3306/bitwarden?charset=utf8&parseTime=True&loc=Local"

      traits:
        - type: storage
          properties:
            pvc:
              - name: object-storage-bitwarden
                mountPath: /data
                accessModes:
                  - ReadWriteOnce
                  - ReadOnlyMany
                resources:
                  requests:
                    storage: 10Gi
                storageClassName: csi-s3
        - type: sslgateway
          properties:
            domain: "bitwarden.saltbo.fun"
            certIssuer: letsencrypt.org
            http:
              "/": 80