apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.statefulset-default-postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
        workload.user.cattle.io/workloadselector: apps.statefulset-default-postgres
    spec:
      affinity: {}
      containers:
        - image: postgres:14-alpine
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 5432
              name: tcp-5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
          envFrom:
            - secretRef:
                name: postgres-secret
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: postgres
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
