apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cert-manager
spec:
  components:
    - name: cert-manager
      type: helm
      properties:
        chart: cert-manager
        version: v1.7.1
        targetNamespace: cert-manager
        url: https://charts.jetstack.io
        repoType: helm
        values:
          installCRDs: true
    - name: cert-manager-issuer
      type: k8s-objects
      properties:
        objects:
          - apiVersion: cert-manager.io/v1
            kind: Issuer
            metadata:
              name: letsencrypt.org
            spec:
              acme:
                server: https://acme-v02.api.letsencrypt.org/directory
                email: saltbo@foxmail.com
                privateKeySecretRef:
                  name: letsencrypt.org
                solvers:
                  - http01:
                      ingress:
                        class: nginx