apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "infra"
resources:
  - ../base
patchesStrategicMerge:
  - storage-class.yaml
  - statefulset.yaml
secretGenerator:
  - name: csi-s3-secret
    envs:
      - csi-s3-secret.txt
  - name: mysql-secret
    envs:
      - mysql-secret.txt
generatorOptions:
  disableNameSuffixHash: true