apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.statefulset-default-mysql
  serviceName: mysql
  template:
    spec:
      affinity: { }
      containers:
        - name: container-0
      nodeSelector:
        usefor.saltbo.cn: boblab
      tolerations:
        - key: "node.kubernetes.io/unschedulable"
          operator: "Exists"
          effect: "NoSchedule"