apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: object-storage-mysql5.6
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-s3