apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.statefulset-default-mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
        workload.user.cattle.io/workloadselector: apps.statefulset-default-mysql
    spec:
      affinity: {}
      containers:
        - image: mysql:5.6
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 3306
              name: 3306tcp
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vol0
          envFrom:
            - secretRef:
                name: mysql-secret
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: vol0
          persistentVolumeClaim:
            claimName: object-storage-mysql5.6
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate