apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: frps
spec:
  components:
    - name: frps
      type: webservice
      properties:
        image: stilleshan/frps
        cmd: [ "/frp/frps", "-c", "/etc/frp/frps.ini" ]
        ports:
          - port: 80
            expose: true
        volumeMounts:
          configMap:
            - name: frps
              cmName: frps
              mountPath: /etc/frp
        env:
          - name: FRP_ADMIN_PASSWD
            valueFrom:
              secretKeyRef:
                name: frps
                key: FRP_ADMIN_PASSWD
          - name: FRP_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: frps
                key: FRP_AUTH_TOKEN
      traits:
        - type: x-gateway
          properties:
            certIssuer: letsencrypt.org
            routes:
              # - domain: "*.dev.saltbo.fun"
              #   enableTLS: true
              #   http:
              #     "/": 80
              - domain: "holly.dev.saltbo.fun"
                enableTLS: true
                http:
                  "/": 80