apiVersion: v1
kind: Service
metadata:
  name: frps-7000
  namespace: default
spec:
  ports:
  - name: tcp-7000
    port: 7000
    protocol: TCP
    targetPort: 7000
    nodePort: 32700
  selector:
    app.oam.dev/component: frps
  type: NodePort