apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rslocald
spec:
  components:
    - name: rslocald
      type: webservice
      properties:
        image: saltbo/rslocald
        ports:
          - port: 8422
            expose: true
          - port: 8423
            expose: true
        volumeMounts:
          configMap:
            - name: rslocald
              cmName: rslocald
              mountPath: /etc/rslocal
      traits:
        - type: x-gateway
          properties:
            certIssuer: letsencrypt.org
            routes:
              - domain: "*.dev.saltbo.fun"
                http:
                  "/": 8423