apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-system
resources:
  - ../base/cert-manager
  # - ../base/storage
  - ../base/mysql
# patchesStrategicMerge:
#   - csi-pv-cos.yaml
  # - mysql.yaml
secretGenerator:
  - name: csi-s3-secret
    envs:
      - csi-s3-secret.txt
  - name: mysql-secret
    envs:
      - mysql-secret.txt
generatorOptions:
  disableNameSuffixHash: true
