apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: gitweb
spec:
  components:
    - name: gitweb
      type: webservice
      properties:
        image: kostyaesmukov/gitweb-readonly
        ports:
          - port: 80

      traits:
        - type: storage
          properties:
            pvc:
              - name: object-storage-git
                mountPath: /var/lib/git
                accessModes:
                  - ReadWriteOnce
                  - ReadOnlyMany
                resources:
                  requests:
                    storage: 10Gi
        - type: sslgateway
          properties:
            domain: "git.saltbo.fun"
            certIssuer: letsencrypt.org
            http:
              "/": 80