apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello
spec:
  components:
    - name: hello
      type: webservice
      properties:
        image: saltbo/hello-world
        port: 8000
      traits:
        - type: sslgateway
          properties:
            domain: hello.saltbo.fun
            certIssuer: letsencrypt.org
            http:
              "/": 8000
